// =============================================================================
// ESP32-S3 Handheld Drone Sniffer - Generated Drone Signatures Database
// AUTO-GENERATED from drone_signatures.json - DO NOT EDIT THIS FILE DIRECTLY
// Edit drone_signatures.json and re-run tools/generate_signatures.py
// =============================================================================
#pragma once

#include <Arduino.h>
#include "config.h"

// -----------------------------------------------------------------------------
// 1. HARDWARE MAC OUIs
// -----------------------------------------------------------------------------
struct KnownDroneOUI {
    uint8_t bytes[3];
    uint8_t vendor;
    const char* name;
};

static const KnownDroneOUI KNOWN_DRONE_OUIS[] PROGMEM = {
    { {0x04, 0xA8, 0x5A}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x0C, 0x9A, 0xE6}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x34, 0xD2, 0x62}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x48, 0x1C, 0xB9}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x4C, 0x43, 0xF6}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x58, 0xB8, 0x58}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x60, 0x60, 0x1F}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x60, 0x81, 0x4A}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x68, 0x7A, 0x49}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x88, 0x29, 0x85}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x8C, 0x58, 0x23}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0xE4, 0x7A, 0x2C}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0xE4, 0x70, 0xB8}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x04, 0x41, 0x69}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x48, 0x10, 0xE5}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x60, 0xFD, 0xA6}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x70, 0x88, 0x6B}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x28, 0x16, 0x7F}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x94, 0x65, 0x2D}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0xAC, 0x67, 0x84}, DRONE_VENDOR_DJI, "DJI Innovations" },
    { {0x28, 0x6D, 0x97}, DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { {0x3C, 0xE9, 0x0E}, DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { {0x64, 0xCE, 0x85}, DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { {0xA0, 0xC9, 0xA0}, DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { {0xC8, 0xD0, 0x88}, DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { {0xB0, 0xD5, 0xCC}, DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { {0x00, 0x12, 0x1C}, DRONE_VENDOR_PARROT, "Parrot Drones" },
    { {0x00, 0x24, 0xE4}, DRONE_VENDOR_PARROT, "Parrot Drones" },
    { {0x00, 0x26, 0x7E}, DRONE_VENDOR_PARROT, "Parrot Drones" },
    { {0x90, 0x03, 0xB7}, DRONE_VENDOR_PARROT, "Parrot Drones" },
    { {0xA0, 0x14, 0x3D}, DRONE_VENDOR_PARROT, "Parrot Drones" },
    { {0x00, 0x0B, 0x6B}, DRONE_VENDOR_SKYDIO, "Skydio / Wistron NeWeb" },
    { {0x38, 0xD2, 0x69}, DRONE_VENDOR_SKYDIO, "Skydio" },
    { {0xEC, 0x50, 0x54}, DRONE_VENDOR_SKYDIO, "Skydio" },
    { {0xE0, 0xB6, 0xF5}, DRONE_VENDOR_YUNEEC, "Yuneec" }
};
static const size_t NUM_KNOWN_OUIS = 35;

// -----------------------------------------------------------------------------
// 2. REMOTE ID & PROTOCOL IDENTIFIERS
// -----------------------------------------------------------------------------
struct RemoteIdProtocol {
    uint8_t length;
    uint8_t bytes[4];
    const char* label;
};

static const RemoteIdProtocol KNOWN_REMOTE_ID_PROTOCOLS[] PROGMEM = {
    { 3, {0xFA, 0x0B, 0xBC, 0x00}, "OpenDroneID (ASTM F3411) OUI" },
    { 2, {0xFF, 0xFA, 0x00, 0x00}, "NAN / ASD-STAN Remote ID Service ID" },
    { 2, {0x88, 0x35, 0x00, 0x00}, "EtherType Drone ID Protocol" },
    { 3, {0x26, 0x37, 0x12, 0x00}, "DJI / French Drone ID OUI" }
};
static const size_t NUM_REMOTE_ID_PROTOCOLS = 4;

// -----------------------------------------------------------------------------
// 3. OPENDRONEID MESSAGE TYPES
// -----------------------------------------------------------------------------
static const uint8_t KNOWN_ODID_MSG_TYPES[] PROGMEM = {
    0x00, 0x10, 0x20, 0x30, 0x40, 0x50, 0xF0
};
static const size_t NUM_ODID_MSG_TYPES = 7;

// -----------------------------------------------------------------------------
// 4. CTA-2063-A MANUFACTURER SERIAL CODES
// -----------------------------------------------------------------------------
struct CTACode {
    char code[5];
    uint8_t vendor;
    const char* name;
};

static const CTACode KNOWN_CTA_MANUFACTURERS[] PROGMEM = {
    { "1581", DRONE_VENDOR_DJI, "DJI Innovations" },
    { "1588", DRONE_VENDOR_AUTEL, "Autel Robotics" },
    { "1622", DRONE_VENDOR_SKYDIO, "Skydio" },
    { "1587", DRONE_VENDOR_PARROT, "Parrot" },
    { "1596", DRONE_VENDOR_YUNEEC, "Yuneec" },
    { "1688", DRONE_VENDOR_GENERIC_FPV, "Teal Drones" },
    { "1798", DRONE_VENDOR_GENERIC_FPV, "senseFly" },
    { "1843", DRONE_VENDOR_GENERIC_FPV, "Wingtra" }
};
static const size_t NUM_CTA_MANUFACTURERS = 8;

// -----------------------------------------------------------------------------
// 5. PACKET SYNC & HEADER BYTES (MAVLink, CRSF, MSP, SBUS)
// -----------------------------------------------------------------------------
struct PacketSyncSignature {
    uint8_t byteVal;
    const char* protocol;
    uint8_t vendor;
};

static const PacketSyncSignature KNOWN_PACKET_SYNCS[] PROGMEM = {
    { 0xFE, "MAVLink 1.0 STX", DRONE_VENDOR_MAVLINK },
    { 0xFD, "MAVLink 2.0 STX", DRONE_VENDOR_MAVLINK },
    { 0xC8, "CRSF / ExpressLRS Sync", DRONE_VENDOR_CRSF_ELRS },
    { 0xEE, "CRSF Frame Address", DRONE_VENDOR_CRSF_ELRS },
    { 0xEC, "CRSF Extended Sync", DRONE_VENDOR_CRSF_ELRS },
    { 0x24, "MSP Header Start '$'", DRONE_VENDOR_MSP },
    { 0x4D, "MSP Header Identifier 'M'", DRONE_VENDOR_MSP },
    { 0x3C, "MSP v1 Command '<'", DRONE_VENDOR_MSP },
    { 0x58, "MSP v2 Frame 'X'", DRONE_VENDOR_MSP },
    { 0x0F, "SBUS Frame Sync", DRONE_VENDOR_GENERIC_FPV },
    { 0x00, "Drone ID / Protocol Prefix", DRONE_VENDOR_GENERIC_FPV }
};
static const size_t NUM_PACKET_SYNCS = 11;

