#!/usr/bin/env python3
"""
generate_signatures.py - Signature Header Generator for ESP32-S3 Drone Sniffer
Reads drone_signatures.json and generates include/drone_signatures.h.
Can be executed standalone or automatically as a PlatformIO extra_scripts pre-build hook.
"""

import json
import os
import sys

def parse_hex_bytes(hex_str):
    """Converts '0xFA0BBC' -> [0xFA, 0x0B, 0xBC]"""
    clean = hex_str.strip().lower().replace("0x", "")
    if len(clean) % 2 != 0:
        clean = "0" + clean
    return [int(clean[i:i+2], 16) for i in range(0, len(clean), 2)]

def generate_header(json_path, output_header_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    lines = [
        "// =============================================================================",
        "// ESP32-S3 Handheld Drone Sniffer - Generated Drone Signatures Database",
        "// AUTO-GENERATED from drone_signatures.json - DO NOT EDIT THIS FILE DIRECTLY",
        "// Edit drone_signatures.json and re-run tools/generate_signatures.py",
        "// =============================================================================",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include \"config.h\"",
        "",
        "// -----------------------------------------------------------------------------",
        "// 1. HARDWARE MAC OUIs",
        "// -----------------------------------------------------------------------------",
        "struct KnownDroneOUI {",
        "    uint8_t bytes[3];",
        "    uint8_t vendor;",
        "    const char* name;",
        "};",
        "",
        "static const KnownDroneOUI KNOWN_DRONE_OUIS[] PROGMEM = {"
    ]

    vendor_map = {
        "DJI": "DRONE_VENDOR_DJI",
        "AUTEL": "DRONE_VENDOR_AUTEL",
        "PARROT": "DRONE_VENDOR_PARROT",
        "SKYDIO": "DRONE_VENDOR_SKYDIO",
        "YUNEEC": "DRONE_VENDOR_YUNEEC",
        "GENERIC": "DRONE_VENDOR_GENERIC_FPV"
    }

    ouis = data.get("hardware_mac_ouis", [])
    for idx, item in enumerate(ouis):
        b = parse_hex_bytes(item["oui"])
        vendor_const = vendor_map.get(item.get("vendor", "").upper(), "DRONE_VENDOR_GENERIC_FPV")
        desc = item.get("description", item["oui"])
        comma = "," if idx < len(ouis) - 1 else ""
        lines.append(f"    {{ {{0x{b[0]:02X}, 0x{b[1]:02X}, 0x{b[2]:02X}}}, {vendor_const}, \"{desc}\" }}{comma}")

    lines.append("};")
    lines.append(f"static const size_t NUM_KNOWN_OUIS = {len(ouis)};")
    lines.append("")

    # -------------------------------------------------------------------------
    # 2. Remote ID & Protocol IDs
    # -------------------------------------------------------------------------
    lines.extend([
        "// -----------------------------------------------------------------------------",
        "// 2. REMOTE ID & PROTOCOL IDENTIFIERS",
        "// -----------------------------------------------------------------------------",
        "struct RemoteIdProtocol {",
        "    uint8_t length;",
        "    uint8_t bytes[4];",
        "    const char* label;",
        "};",
        "",
        "static const RemoteIdProtocol KNOWN_REMOTE_ID_PROTOCOLS[] PROGMEM = {"
    ])

    protocols = data.get("remote_id_and_protocols", [])
    for idx, item in enumerate(protocols):
        b = parse_hex_bytes(item["id"])
        b_padded = (b + [0, 0, 0, 0])[:4]
        comma = "," if idx < len(protocols) - 1 else ""
        hex_bytes_str = ", ".join(f"0x{x:02X}" for x in b_padded)
        lines.append(f"    {{ {len(b)}, {{{hex_bytes_str}}}, \"{item['label']}\" }}{comma}")

    lines.append("};")
    lines.append(f"static const size_t NUM_REMOTE_ID_PROTOCOLS = {len(protocols)};")
    lines.append("")

    # -------------------------------------------------------------------------
    # 3. OpenDroneID Message Types
    # -------------------------------------------------------------------------
    lines.extend([
        "// -----------------------------------------------------------------------------",
        "// 3. OPENDRONEID MESSAGE TYPES",
        "// -----------------------------------------------------------------------------",
        "static const uint8_t KNOWN_ODID_MSG_TYPES[] PROGMEM = {"
    ])

    msg_types = data.get("opendroneid_message_types", [])
    type_strs = [f"0x{parse_hex_bytes(t['type'])[0]:02X}" for t in msg_types]
    lines.append("    " + ", ".join(type_strs))
    lines.append("};")
    lines.append(f"static const size_t NUM_ODID_MSG_TYPES = {len(msg_types)};")
    lines.append("")

    # -------------------------------------------------------------------------
    # 4. CTA-2063-A Manufacturer Codes
    # -------------------------------------------------------------------------
    lines.extend([
        "// -----------------------------------------------------------------------------",
        "// 4. CTA-2063-A MANUFACTURER SERIAL CODES",
        "// -----------------------------------------------------------------------------",
        "struct CTACode {",
        "    char code[5];",
        "    uint8_t vendor;",
        "    const char* name;",
        "};",
        "",
        "static const CTACode KNOWN_CTA_MANUFACTURERS[] PROGMEM = {"
    ])

    cta_items = data.get("cta_2063_manufacturers", [])
    for idx, item in enumerate(cta_items):
        v_name = item.get("vendor", "")
        # map vendor
        if "DJI" in v_name.upper():
            v_const = "DRONE_VENDOR_DJI"
        elif "AUTEL" in v_name.upper():
            v_const = "DRONE_VENDOR_AUTEL"
        elif "SKYDIO" in v_name.upper():
            v_const = "DRONE_VENDOR_SKYDIO"
        elif "PARROT" in v_name.upper():
            v_const = "DRONE_VENDOR_PARROT"
        elif "YUNEEC" in v_name.upper():
            v_const = "DRONE_VENDOR_YUNEEC"
        else:
            v_const = "DRONE_VENDOR_GENERIC_FPV"
        comma = "," if idx < len(cta_items) - 1 else ""
        lines.append(f"    {{ \"{item['code']}\", {v_const}, \"{v_name}\" }}{comma}")

    lines.append("};")
    lines.append(f"static const size_t NUM_CTA_MANUFACTURERS = {len(cta_items)};")
    lines.append("")

    # -------------------------------------------------------------------------
    # 5. Packet Sync & Header Bytes
    # -------------------------------------------------------------------------
    lines.extend([
        "// -----------------------------------------------------------------------------",
        "// 5. PACKET SYNC & HEADER BYTES (MAVLink, CRSF, MSP, SBUS)",
        "// -----------------------------------------------------------------------------",
        "struct PacketSyncSignature {",
        "    uint8_t byteVal;",
        "    const char* protocol;",
        "    uint8_t vendor;",
        "};",
        "",
        "static const PacketSyncSignature KNOWN_PACKET_SYNCS[] PROGMEM = {"
    ])

    syncs = data.get("packet_sync_bytes", [])
    for idx, item in enumerate(syncs):
        b = parse_hex_bytes(item["byte"])[0]
        proto = item.get("protocol", "")
        if "MAVLINK" in proto.upper():
            v_const = "DRONE_VENDOR_MAVLINK"
        elif "CRSF" in proto.upper() or "ELRS" in proto.upper():
            v_const = "DRONE_VENDOR_CRSF_ELRS"
        elif "MSP" in proto.upper():
            v_const = "DRONE_VENDOR_MSP"
        else:
            v_const = "DRONE_VENDOR_GENERIC_FPV"
        comma = "," if idx < len(syncs) - 1 else ""
        lines.append(f"    {{ 0x{b:02X}, \"{proto}\", {v_const} }}{comma}")

    lines.append("};")
    lines.append(f"static const size_t NUM_PACKET_SYNCS = {len(syncs)};")
    lines.append("")

    with open(output_header_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")

    print(f"[OK] Generated {output_header_path} from {json_path}")
    print(f"     - OUIs: {len(ouis)} entries")
    print(f"     - Remote ID Protocols: {len(protocols)} entries")
    print(f"     - OpenDroneID Message Types: {len(msg_types)} entries")
    print(f"     - CTA-2063-A Manufacturer Codes: {len(cta_items)} entries")
    print(f"     - Packet Sync Signatures: {len(syncs)} entries")

def main():
    proj_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    json_path = os.path.join(proj_dir, "drone_signatures.json")
    header_path = os.path.join(proj_dir, "include", "drone_signatures.h")

    if not os.path.exists(json_path):
        print(f"[ERROR] JSON file not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    generate_header(json_path, header_path)

# PlatformIO extra_scripts integration hook
try:
    import SCons.Script
    # Running inside PlatformIO SCons build environment
    Import("env")
    proj_dir = env.get("PROJECT_DIR", ".")
    json_path = os.path.join(proj_dir, "drone_signatures.json")
    header_path = os.path.join(proj_dir, "include", "drone_signatures.h")
    if os.path.exists(json_path):
        generate_header(json_path, header_path)
except Exception:
    pass

if __name__ == "__main__":
    main()
